/**
 * Sources registry.
 *
 * Every prose page renders a Sources section drawn from this catalog.
 * To cite a fact, add the source key to that page's `sources` array.
 * To add a new source, add an entry here — keys are stable across the codebase.
 *
 * Rule: every numerical constant, every quoted line, every historical
 * attribution, every order-of-magnitude claim must be backed by a primary
 * or canonical secondary source listed here. No claim from training data
 * without a citation.
 */

export interface Source {
  id: string;
  title: string;
  author: string;
  /** Publication year */
  year?: number;
  /** Journal / publisher */
  venue?: string;
  /** Volume, issue, page numbers if applicable */
  locator?: string;
  /** Public URL */
  url?: string;
  /** Optional note: what page/section was used and what claim it backs */
  note?: string;
}

export const SOURCES: Record<string, Source> = {
  /* ─── Primary textbooks ─── */
  'feynman-II-27': {
    id: 'feynman-II-27',
    title: 'The Feynman Lectures on Physics, Vol. II, Ch. 27 — Field Energy and Field Momentum',
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_27.html',
    note: 'Source for the Poynting-vector treatment of resistive wires and the "flow of energy into the wire all around" quote.',
  },
  'feynman-II-2': {
    id: 'feynman-II-2',
    title: 'The Feynman Lectures on Physics, Vol. II, Ch. 2 — Differential Calculus of Vector Fields',
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_02.html',
    note: 'Conservative-field / curl-free property of static E and its potential representation.',
  },
  'feynman-II-13': {
    id: 'feynman-II-13',
    title: 'The Feynman Lectures on Physics, Vol. II, Ch. 13 — Magnetostatics',
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_13.html',
    note: 'Biot–Savart, Ampère, and the relativistic origin of magnetism.',
  },
  'feynman-II-17': {
    id: 'feynman-II-17',
    title: 'The Feynman Lectures on Physics, Vol. II, Ch. 17 — The Laws of Induction',
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_17.html',
    note: "Faraday's law and Lenz's-law sign convention.",
  },
  'griffiths-2017': {
    id: 'griffiths-2017',
    title: 'Introduction to Electrodynamics, 4th ed.',
    author: 'David J. Griffiths',
    year: 2017,
    venue: 'Cambridge University Press',
    note: 'Standard undergraduate reference for derivations of Coulomb, Gauss, Ampère, Faraday, Poynting and the Drude model. Specific sections cited per-page.',
  },
  'jackson-1999': {
    id: 'jackson-1999',
    title: 'Classical Electrodynamics, 3rd ed.',
    author: 'John David Jackson',
    year: 1999,
    venue: 'Wiley',
    note: 'Graduate reference for displacement current, energy density, Poynting flux, and relativistic transformation of E and B.',
  },
  'ashcroft-mermin-1976': {
    id: 'ashcroft-mermin-1976',
    title: 'Solid State Physics',
    author: 'Neil W. Ashcroft, N. David Mermin',
    year: 1976,
    venue: 'Holt, Rinehart & Winston',
    note: 'Drude model (Ch. 1), Fermi velocity, and free-electron densities n for conducting metals.',
  },
  'kittel-2005': {
    id: 'kittel-2005',
    title: 'Introduction to Solid State Physics, 8th ed.',
    author: 'Charles Kittel',
    year: 2005,
    venue: 'Wiley',
    note: 'Fermi velocity of copper ~1.57×10⁶ m/s, electrical resistivity tables.',
  },

  /* ─── Reference data ─── */
  'codata-2018': {
    id: 'codata-2018',
    title: 'CODATA Recommended Values of the Fundamental Physical Constants: 2018',
    author: 'E. Tiesinga, P. J. Mohr, D. B. Newell, B. N. Taylor',
    year: 2021,
    venue: 'Rev. Mod. Phys. 93, 025010',
    url: 'https://physics.nist.gov/cuu/Constants/',
    note: 'Source for e, m_e, m_p, ε₀, μ₀ (post-2019 SI), c (exact), G, k_B, σ_SB used throughout.',
  },
  'crc-resistivity': {
    id: 'crc-resistivity',
    title: 'CRC Handbook of Chemistry and Physics, 104th ed., "Electrical Resistivity of Pure Metals" at 20 °C',
    author: 'John R. Rumble (ed.)',
    year: 2023,
    venue: 'CRC Press / Taylor & Francis',
    note: 'Conductivities of Cu, Ag, Au, Al, Fe, W at room temperature.',
  },
  'kanthal': {
    id: 'kanthal',
    title: 'Nichrome 80 / Kanthal A1 — manufacturer datasheet',
    author: 'Sandvik / Kanthal',
    year: 2024,
    venue: 'Materials data sheet',
    url: 'https://www.kanthal.com/en/products/material-datasheets/wire/resistance-heating-wire-and-resistance-wire/nikrothal-80/',
    note: 'Resistivity ρ ≈ 1.1×10⁻⁶ Ω·m (σ ≈ 9×10⁵ S/m) for the canonical heating alloy.',
  },
  'libretexts-conduction': {
    id: 'libretexts-conduction',
    title: 'University Physics II — §9.3 Model of Conduction in Metals',
    author: 'OpenStax / LibreTexts',
    year: 2023,
    url: 'https://phys.libretexts.org/Bookshelves/University_Physics/University_Physics_(OpenStax)/University_Physics_II_-_Thermodynamics_Electricity_and_Magnetism_(OpenStax)/09:_Current_and_Resistance/9.03:_Model_of_Conduction_in_Metals',
    note: 'Drift velocity of 0.02 mm/s for 12-gauge Cu @ 20 A; signal speed ~⅔ c in copper; collision time τ ~2×10⁻¹⁴ s.',
  },

  /* ─── Journal articles ─── */
  'davis-kaplan-2011': {
    id: 'davis-kaplan-2011',
    title: 'Poynting vector flow in a circular circuit',
    author: 'Basil S. Davis, Lev Kaplan',
    year: 2011,
    venue: 'American Journal of Physics 79, 1155–1162',
    url: 'https://pubs.aip.org/aapt/ajp/article/79/11/1155/1056381/Poynting-vector-flow-in-a-circular-circuit',
    note: 'Full 3D numerical treatment showing Poynting flux into a resistive ring-shaped wire equals the dissipated power. Confirms the 2D toy model generalizes.',
  },
  'morris-styer-2012': {
    id: 'morris-styer-2012',
    title: 'Visualizing Poynting vector energy flow in electric circuits',
    author: 'Daniel F. Styer (lecture notes)',
    year: 2012,
    venue: 'Oberlin College Electrodynamics course materials',
    url: 'https://www2.oberlin.edu/physics/dstyer/Electrodynamics/VisualizingZ.pdf',
    note: 'Practical visualization of Poynting flow, including the 2D infinite-parallel-rail toy in which the flow lines are exactly along equipotentials.',
  },
  'cavendish-1773': {
    id: 'cavendish-1773',
    title: 'Henry Cavendish, "Experiments on Electricity" (1771–1781 notes, esp. 1773 null-cavity test), in The Electrical Researches of the Honourable Henry Cavendish',
    author: 'James Clerk Maxwell (ed.)',
    year: 1879,
    venue: 'Cambridge University Press',
    note: 'Cavendish concluded in 1773 that the inverse-square exponent could differ from 2 by no more than ~1/50 (|deviation| < 0.02) — the first precision test. Maxwell & MacAlister refined the bound to ~1/21600 in 1877.',
  },
  'williams-faller-hill-1971': {
    id: 'williams-faller-hill-1971',
    title: "New Experimental Test of Coulomb's Law: A Laboratory Upper Limit on the Photon Rest Mass",
    author: 'E. R. Williams, J. E. Faller, H. A. Hill',
    year: 1971,
    venue: 'Physical Review Letters 26, 721',
    url: 'https://doi.org/10.1103/PhysRevLett.26.721',
    note: "Writing the deviation as 1/r^(2+q), the experiment bounded q = (2.7 ± 3.1)×10⁻¹⁶ — i.e., the exponent is 2 to within ~3×10⁻¹⁶.",
  },
  'coulomb-1785': {
    id: 'coulomb-1785',
    title: 'Premier mémoire sur l\'électricité et le magnétisme',
    author: 'Charles-Augustin de Coulomb',
    year: 1785,
    venue: 'Histoire de l\'Académie Royale des Sciences',
    note: 'Original torsion-balance experiment establishing the inverse-square law for electric force.',
  },
  'faraday-1832': {
    id: 'faraday-1832',
    title: 'Experimental Researches in Electricity. — First Series',
    author: 'Michael Faraday',
    year: 1832,
    venue: 'Philosophical Transactions of the Royal Society of London 122, 125–162',
    url: 'https://royalsocietypublishing.org/doi/10.1098/rstl.1832.0006',
    note: 'Discovery of electromagnetic induction.',
  },
  'maxwell-1865': {
    id: 'maxwell-1865',
    title: 'A Dynamical Theory of the Electromagnetic Field',
    author: 'James Clerk Maxwell',
    year: 1865,
    venue: 'Philosophical Transactions of the Royal Society of London 155, 459–512',
    url: 'https://royalsocietypublishing.org/doi/10.1098/rstl.1865.0008',
    note: 'Introduces displacement current and completes Ampère\'s law, predicting EM waves at speed c.',
  },
  'poynting-1884': {
    id: 'poynting-1884',
    title: 'On the Transfer of Energy in the Electromagnetic Field',
    author: 'John Henry Poynting',
    year: 1884,
    venue: 'Philosophical Transactions of the Royal Society of London 175, 343–361',
    url: 'https://royalsocietypublishing.org/doi/10.1098/rstl.1884.0016',
    note: 'Derivation of S = (1/μ₀)E×B and energy-conservation theorem for EM fields.',
  },
  'drude-1900': {
    id: 'drude-1900',
    title: 'Zur Elektronentheorie der Metalle',
    author: 'Paul Drude',
    year: 1900,
    venue: 'Annalen der Physik 306 (3), 566–613',
    note: 'Original classical free-electron model of metallic conduction.',
  },
  'biot-savart-1820': {
    id: 'biot-savart-1820',
    title: 'Note sur le magnétisme de la pile de Volta',
    author: 'Jean-Baptiste Biot, Félix Savart',
    year: 1820,
    venue: 'Annales de Chimie et de Physique 15, 222–223',
    note: 'Empirical 1/r² fall-off of magnetic field from a current element.',
  },
  'ampere-1826': {
    id: 'ampere-1826',
    title: 'Théorie mathématique des phénomènes électrodynamiques uniquement déduite de l\'expérience',
    author: 'André-Marie Ampère',
    year: 1826,
    venue: 'Académie des Sciences, Paris',
    note: 'Force law between current elements; what we now call Ampère\'s circuital law.',
  },
  'gauss-1813': {
    id: 'gauss-1813',
    title: 'Theoria attractionis corporum sphaeroidicorum ellipticorum',
    author: 'Carl Friedrich Gauss',
    year: 1813,
    venue: 'Commentationes societatis regiae scientiarum Gottingensis recentiores',
    note: 'Original divergence theorem (Gauss\'s theorem) — later applied to electrostatics.',
  },
  'hall-1879': {
    id: 'hall-1879',
    title: 'On a New Action of the Magnet on Electric Currents',
    author: 'Edwin Hall',
    year: 1879,
    venue: 'American Journal of Mathematics 2, 287',
    note: 'Discovery of the Hall effect — sign of charge carriers in conductors.',
  },
  'joule-1841': {
    id: 'joule-1841',
    title: 'On the Heat Evolved by Metallic Conductors of Electricity',
    author: 'James Prescott Joule',
    year: 1841,
    venue: 'Philosophical Magazine 19, 260',
    note: 'Original measurement of P = I²R heating in resistive wires.',
  },
  'onnes-1911': {
    id: 'onnes-1911',
    title: 'Further experiments with liquid helium. C. On the change of electric resistance of pure metals at very low temperatures etc. IV. The resistance of pure mercury at helium temperatures',
    author: 'Heike Kamerlingh Onnes',
    year: 1911,
    venue: 'Communications from the Physical Laboratory of the University of Leiden, No. 120b / 122b',
    note: 'Discovery of superconductivity: mercury\'s resistance drops abruptly to zero at 4.2 K.',
  },
  'bcs-1957': {
    id: 'bcs-1957',
    title: 'Theory of Superconductivity',
    author: 'J. Bardeen, L. N. Cooper, J. R. Schrieffer',
    year: 1957,
    venue: 'Physical Review 108, 1175',
    url: 'https://doi.org/10.1103/PhysRev.108.1175',
    note: 'BCS theory: phonon-mediated electron pairing explains the gap and zero DC resistance of superconductors.',
  },
  'matthiessen-1864': {
    id: 'matthiessen-1864',
    title: 'On the influence of temperature on the electric conducting-power of alloys',
    author: 'Augustus Matthiessen, Charles Vogt',
    year: 1864,
    venue: 'Philosophical Transactions of the Royal Society of London 154, 167–200',
    note: 'Matthiessen\'s rule: ρ(T) = ρ_residual + ρ_phonon(T); resistivity of pure metals is roughly linear in T above the Debye temperature.',
  },
  'nec-2017-aluminum': {
    id: 'nec-2017-aluminum',
    title: 'CPSC Publication #516 — Repairing Aluminum Wiring',
    author: 'U.S. Consumer Product Safety Commission',
    year: 2011,
    url: 'https://www.cpsc.gov/safety-education/safety-guides/home/repairing-aluminum-wiring',
    note: 'Solid-aluminum branch-circuit wiring (15 A / 20 A) installed in U.S. homes 1965–1973 was implicated in connection-overheating fires; oxide layer and creep at terminations were the root causes.',
  },
  'grainger-power-systems-2003': {
    id: 'grainger-power-systems-2003',
    title: 'Power System Analysis',
    author: 'John J. Grainger, William D. Stevenson Jr.',
    year: 1994,
    venue: 'McGraw-Hill',
    note: 'Transmission-line losses scale as P_loss = (P_load/V)² R; raising V reduces I for a given delivered P, cutting I²R losses quadratically.',
  },
  'irwin-circuit-analysis-2015': {
    id: 'irwin-circuit-analysis-2015',
    title: 'Basic Engineering Circuit Analysis, 11th ed.',
    author: 'J. David Irwin, R. Mark Nelms',
    year: 2015,
    venue: 'Wiley',
    note: 'Impedance Z = R + jX as the AC generalization of resistance; reactive components store energy rather than dissipate it.',
  },

  /* ─── Online references ─── */
  'hyperphysics-emag': {
    id: 'hyperphysics-emag',
    title: 'HyperPhysics — Electricity and Magnetism',
    author: 'Carl R. Nave, Georgia State University',
    year: 2020,
    url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/electric/elecon.html',
    note: 'Cross-checked numerical examples and derivation summaries for undergraduate EM topics.',
  },
  'libretexts-univ-physics': {
    id: 'libretexts-univ-physics',
    title: 'OpenStax University Physics II — Electricity & Magnetism',
    author: 'OpenStax / LibreTexts',
    year: 2023,
    url: 'https://phys.libretexts.org/Bookshelves/University_Physics/University_Physics_(OpenStax)/University_Physics_II_-_Thermodynamics_Electricity_and_Magnetism_(OpenStax)',
    note: 'Open-access undergraduate text used as a cross-reference for numbers and worked examples.',
  },
  'nist-codata': {
    id: 'nist-codata',
    title: 'NIST Reference on Constants, Units, and Uncertainty',
    author: 'National Institute of Standards and Technology',
    year: 2022,
    url: 'https://physics.nist.gov/cuu/Constants/',
    note: 'Canonical source for SI fundamental constants used in src/lib/physics.ts.',
  },

  /* ─── New for Ch7–Ch11 ─── */
  'hertz-1888': {
    id: 'hertz-1888',
    title: 'Über elektromagnetische Wellen im Lufte und deren Reflexion (On Electromagnetic Waves in Air and Their Reflection)',
    author: 'Heinrich Hertz',
    year: 1888,
    venue: 'Annalen der Physik 270 (8), 609–623',
    note: 'First experimental detection of electromagnetic waves predicted by Maxwell; standing waves between parallel reflectors gave a propagation speed consistent with c.',
  },
  'feynman-II-18': {
    id: 'feynman-II-18',
    title: "The Feynman Lectures on Physics, Vol. II, Ch. 18 — The Maxwell Equations",
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_18.html',
    note: "Compact synthesis of the four Maxwell equations and Maxwell's displacement-current addition to Ampère's law.",
  },
  'feynman-II-21': {
    id: 'feynman-II-21',
    title: 'The Feynman Lectures on Physics, Vol. II, Ch. 21 — Solutions of Maxwell\'s Equations with Currents and Charges',
    author: 'Richard P. Feynman, Robert B. Leighton, Matthew Sands',
    year: 1964,
    venue: 'Caltech / Addison-Wesley',
    url: 'https://www.feynmanlectures.caltech.edu/II_21.html',
    note: 'Radiation from accelerating charges; the formula for the far-field of an oscillating dipole.',
  },
  'einstein-1905': {
    id: 'einstein-1905',
    title: 'Zur Elektrodynamik bewegter Körper (On the Electrodynamics of Moving Bodies)',
    author: 'Albert Einstein',
    year: 1905,
    venue: 'Annalen der Physik 17 (10), 891–921',
    url: 'https://einsteinpapers.press.princeton.edu/vol2-trans/154',
    note: 'Special relativity, motivated explicitly by the electrodynamics of moving bodies. Section 9 shows how E and B transform between inertial frames.',
  },
  'purcell-morin-2013': {
    id: 'purcell-morin-2013',
    title: 'Electricity and Magnetism, 3rd ed.',
    author: 'Edward M. Purcell, David J. Morin',
    year: 2013,
    venue: 'Cambridge University Press',
    note: "Treats magnetism as the relativistic consequence of moving charge from the start — the textbook Feynman gestures at in Vol II Ch. 13. Ch. 5–6 derive B from a Lorentz-boosted Coulomb force.",
  },
  'kirchhoff-1845': {
    id: 'kirchhoff-1845',
    title: 'Über den Durchgang eines elektrischen Stromes durch eine Ebene, insbesondere durch eine kreisförmige (On the passage of an electric current through a plane, in particular a circular one)',
    author: 'Gustav Kirchhoff',
    year: 1845,
    venue: 'Annalen der Physik 140 (4), 497–514',
    note: "Kirchhoff's current and voltage laws for circuits.",
  },
  'horowitz-hill-2015': {
    id: 'horowitz-hill-2015',
    title: 'The Art of Electronics, 3rd ed.',
    author: 'Paul Horowitz, Winfield Hill',
    year: 2015,
    venue: 'Cambridge University Press',
    note: 'Working engineer\'s reference for practical AC, impedance, op-amps, and signal-handling; cross-checked numerical examples for Ch.10.',
  },
  'nilsson-riedel-2018': {
    id: 'nilsson-riedel-2018',
    title: 'Electric Circuits, 11th ed.',
    author: 'James W. Nilsson, Susan A. Riedel',
    year: 2018,
    venue: 'Pearson',
    note: 'Standard undergraduate circuits text. Reference for nodal analysis, transient response of RC/RL/RLC networks, and operating-point computation.',
  },
  'ho-ruehli-brennan-1975': {
    id: 'ho-ruehli-brennan-1975',
    title: 'The Modified Nodal Approach to Network Analysis',
    author: 'Chung-Wen Ho, Albert E. Ruehli, Pierce A. Brennan',
    year: 1975,
    venue: 'IEEE Transactions on Circuits and Systems CAS-22 (6), 504–509',
    note: 'Original MNA formulation: augment Kirchhoff current equations with branch-current unknowns for voltage sources and inductors. The matrix shape used by SPICE and by this lab.',
  },
  'shockley-1949': {
    id: 'shockley-1949',
    title: 'The Theory of p-n Junctions in Semiconductors and p-n Junction Transistors',
    author: 'William Shockley',
    year: 1949,
    venue: 'Bell System Technical Journal 28 (3), 435–489',
    note: 'Original derivation of the diode equation I = Iₛ (exp(qV/kT) − 1). The piecewise-linear "0.7 V drop, small on-resistance" approximation used in this lab is the standard textbook simplification of that curve.',
  },
  'clausius-1850': {
    id: 'clausius-1850',
    title: 'Ueber die Art der Bewegung, welche wir Wärme nennen / Polarization in dielectrics (Clausius–Mossotti work, 1850s)',
    author: 'Rudolf Clausius (with O. F. Mossotti, 1846)',
    year: 1850,
    venue: 'Annalen der Physik (and later Mossotti, Mem. Soc. Ital. Sci. Modena 1846)',
    note: 'Clausius–Mossotti relation linking molecular polarizability to bulk permittivity εᵣ.',
  },
  'langevin-1905': {
    id: 'langevin-1905',
    title: 'Magnétisme et théorie des électrons (Magnetism and the Theory of Electrons)',
    author: 'Paul Langevin',
    year: 1905,
    venue: 'Annales de Chimie et de Physique 5, 70–127',
    note: 'Classical theory of dia- and paramagnetism; the Langevin function describes the equilibrium magnetization of independent magnetic dipoles.',
  },
  'weiss-1907': {
    id: 'weiss-1907',
    title: "L'hypothèse du champ moléculaire et la propriété ferromagnétique (Molecular Field Hypothesis and the Ferromagnetic Property)",
    author: 'Pierre Weiss',
    year: 1907,
    venue: 'Journal de Physique Théorique et Appliquée 6, 661–690',
    note: 'Weiss molecular-field theory and the magnetic-domain picture explaining hysteresis in ferromagnets.',
  },
  'debye-1929': {
    id: 'debye-1929',
    title: 'Polar Molecules',
    author: 'Peter Debye',
    year: 1929,
    venue: 'Chemical Catalog Company / Dover reprint',
    note: 'Frequency dependence of εᵣ in polar liquids (Debye relaxation); origin of the large static εᵣ ≈ 80 of water.',
  },

  /* ─── Case-study sources ─── */
  'rakov-uman-2003': {
    id: 'rakov-uman-2003',
    title: 'Lightning: Physics and Effects',
    author: 'Vladimir A. Rakov, Martin A. Uman',
    year: 2003,
    venue: 'Cambridge University Press',
    note: 'Standard reference for lightning parameters: ~10⁸–10⁹ V cloud-to-ground potential difference, ~30 kA median peak return-stroke current (negative CG), ~5 C median charge transferred per flash.',
  },
  'uman-2001': {
    id: 'uman-2001',
    title: 'The Lightning Discharge, 2nd ed.',
    author: 'Martin A. Uman',
    year: 2001,
    venue: 'Dover Publications',
    note: 'Canonical monograph on lightning physics: stepped leader, return-stroke currents, charge transfer per stroke, and channel electric fields.',
  },
  'usb-pd-r3': {
    id: 'usb-pd-r3',
    title: 'USB Power Delivery Specification, Revision 3.1 (Extended Power Range)',
    author: 'USB Implementers Forum',
    year: 2021,
    venue: 'USB-IF',
    url: 'https://www.usb.org/document-library/usb-power-delivery',
    note: 'Defines EPR modes up to 48 V / 5 A = 240 W over USB Type-C; e-marker requirements for ≥5 A cables.',
  },
  'catania-2015': {
    id: 'catania-2015',
    title: 'Electric Eels Concentrate Their Electric Field to Induce Involuntary Fatigue in Struggling Prey',
    author: 'Kenneth C. Catania',
    year: 2015,
    venue: 'Current Biology 25 (22), 2889–2898',
    url: 'https://doi.org/10.1016/j.cub.2015.09.036',
    note: 'Direct measurements of Electrophorus electricus discharges: peak voltage ~600 V, peak current ~1 A in short bursts during predatory strikes.',
  },
  'coaton-marsden-1997': {
    id: 'coaton-marsden-1997',
    title: 'Lamps and Lighting, 4th ed.',
    author: 'John R. Coaton, Arthur M. Marsden (eds.)',
    year: 1997,
    venue: 'Arnold / Wiley',
    note: 'Standard reference for incandescent-lamp engineering: tungsten filament operating temperature ~2700–3000 K, luminous efficacy ~10–15 lm/W, ~5–10% radiative efficiency in the visible.',
  },

  /* ─── Ch4 / Ch5 / Ch6 case-study sources ─── */
  'lauterbur-1973': {
    id: 'lauterbur-1973',
    title: 'Image Formation by Induced Local Interactions: Examples Employing Nuclear Magnetic Resonance',
    author: 'Paul C. Lauterbur',
    year: 1973,
    venue: 'Nature 242, 190–191',
    url: 'https://doi.org/10.1038/242190a0',
    note: 'Original paper demonstrating MRI ("zeugmatography") via field gradients on top of a strong static B₀. Foundational reference for clinical MRI scanners.',
  },
  'bruning-lhc-2004': {
    id: 'bruning-lhc-2004',
    title: 'LHC Design Report, Vol. I: The LHC Main Ring',
    author: 'O. S. Brüning, P. Collier, P. Lebrun, S. Myers, R. Ostojic, J. Poole, P. Proudlock (eds.)',
    year: 2004,
    venue: 'CERN-2004-003',
    url: 'https://cds.cern.ch/record/782076',
    note: 'Official design report for the LHC: 1232 superconducting NbTi dipole magnets at 8.33 T nominal for 7 TeV beams; 27 km ring circumference; 11,850 A coil current at 1.9 K.',
  },
  'chulliat-wmm-2020': {
    id: 'chulliat-wmm-2020',
    title: 'The US/UK World Magnetic Model for 2020–2025: Technical Report',
    author: 'A. Chulliat, W. Brown, P. Alken, C. Beggan, M. Nair, G. Cox, A. Woods, S. Macmillan, B. Meyer, M. Paniccia',
    year: 2020,
    venue: 'NOAA National Centers for Environmental Information / British Geological Survey',
    url: 'https://www.ncei.noaa.gov/products/world-magnetic-model',
    note: 'Geomagnetic field model giving total intensity ~25,000–65,000 nT across Earth\'s surface (~0.25–0.65 G).',
  },
  'duncan-thompson-1992': {
    id: 'duncan-thompson-1992',
    title: 'Formation of Very Strongly Magnetized Neutron Stars: Implications for Gamma-Ray Bursts',
    author: 'Robert C. Duncan, Christopher Thompson',
    year: 1992,
    venue: 'Astrophysical Journal 392, L9–L13',
    url: 'https://doi.org/10.1086/186413',
    note: 'Magnetar model: neutron stars with surface dipole fields B ~10¹⁴–10¹⁵ G (10¹⁰–10¹¹ T), powered by decay of the magnetic field.',
  },
  'wpc-qi-1.3': {
    id: 'wpc-qi-1.3',
    title: 'Qi Wireless Power Transfer System Specification, Volume I, Part 1: General Requirements (v1.3)',
    author: 'Wireless Power Consortium',
    year: 2021,
    venue: 'WPC',
    url: 'https://www.wirelesspowerconsortium.com/knowledge-base/specifications/',
    note: 'Qi specification: baseline 5 W BPP and extended 15 W EPP modes; operating frequency 110–205 kHz; tightly-coupled planar coils.',
  },
  'lucia-induction-2014': {
    id: 'lucia-induction-2014',
    title: 'Induction Heating Technology and Its Applications: Past Developments, Current Technology, and Future Challenges',
    author: 'Óscar Lucía, Pascal Maussion, Enrique J. Dede, José M. Burdío',
    year: 2014,
    venue: 'IEEE Transactions on Industrial Electronics 61 (5), 2509–2520',
    url: 'https://doi.org/10.1109/TIE.2013.2281162',
    note: 'Survey of domestic induction-heating appliances: typical operating range 20–100 kHz, 1.5–3.7 kW power, ~85–90% wall-to-cookware efficiency.',
  },
  'kopp-lean-2011': {
    id: 'kopp-lean-2011',
    title: 'A new, lower value of total solar irradiance: Evidence and climate significance',
    author: 'Greg Kopp, Judith L. Lean',
    year: 2011,
    venue: 'Geophysical Research Letters 38, L01706',
    url: 'https://doi.org/10.1029/2010GL045777',
    note: 'TIM/SORCE measurement of the solar constant: 1360.8 ± 0.5 W/m² at 1 AU during the 2008 solar minimum — the modern accepted value of the top-of-atmosphere Poynting flux from the Sun.',
  },
  'pozar-2011': {
    id: 'pozar-2011',
    title: 'Microwave Engineering, 4th ed.',
    author: 'David M. Pozar',
    year: 2011,
    venue: 'Wiley',
    note: 'Standard reference for transmission lines: coaxial-cable TEM mode propagation, characteristic impedance Z₀ = (η/2π)·ln(b/a)/√εᵣ, and the fact that the time-averaged Poynting flux integrated over the dielectric cross-section equals VI for the lossless line.',
  },
  'green-bohn-2015': {
    id: 'green-bohn-2015',
    title: 'Status of Energy Storage and Distribution by Superconducting Cables',
    author: 'Mark A. Green, A. Bohn et al.',
    year: 2015,
    venue: 'IEEE Transactions on Applied Superconductivity 25 (3), 5400305',
    url: 'https://doi.org/10.1109/TASC.2014.2386931',
    note: 'Review of in-service HTS power cables (Yokohama / Albany / Essen projects): 66 kV class operation, multi-kA currents, near-zero ohmic loss in the superconductor itself.',
  },

  /* ─── Ch10 / Ch11 case-study sources ─── */
  'ansi-c84-1-2020': {
    id: 'ansi-c84-1-2020',
    title: 'ANSI C84.1-2020 — American National Standard for Electric Power Systems and Equipment — Voltage Ratings (60 Hz)',
    author: 'National Electrical Manufacturers Association (NEMA)',
    year: 2020,
    venue: 'NEMA / ANSI',
    url: 'https://www.nema.org/standards/view/american-national-standard-for-electric-power-systems-and-equipment-voltage-ratings-60-hertz',
    note: 'Nominal North-American service voltages: 120/240 V split-phase residential; 208 Y/120, 480 Y/277 V commercial three-phase; standard transmission classes from 69 kV through 765 kV.',
  },
  'erickson-maksimovic-2020': {
    id: 'erickson-maksimovic-2020',
    title: 'Fundamentals of Power Electronics, 3rd ed.',
    author: 'Robert W. Erickson, Dragan Maksimović',
    year: 2020,
    venue: 'Springer',
    note: 'Standard graduate text on switched-mode power conversion: buck/boost topologies, transformer-isolated flyback and forward converters; typical 85–95% conversion efficiencies vs the ~50% achievable with a linear regulator stepping down from rectified mains.',
  },
  'baibich-1988': {
    id: 'baibich-1988',
    title: 'Giant Magnetoresistance of (001)Fe/(001)Cr Magnetic Superlattices',
    author: 'M. N. Baibich, J. M. Broto, A. Fert, F. Nguyen Van Dau, F. Petroff, P. Etienne, G. Creuzet, A. Friederich, J. Chazelas',
    year: 1988,
    venue: 'Physical Review Letters 61, 2472–2475',
    url: 'https://doi.org/10.1103/PhysRevLett.61.2472',
    note: 'Discovery of giant magnetoresistance in Fe/Cr multilayers — ~50% resistance change at 4.2 K in applied fields of a few tesla. Shared basis (with Grünberg) of the 2007 Nobel Prize in Physics.',
  },
  'binasch-grunberg-1989': {
    id: 'binasch-grunberg-1989',
    title: 'Enhanced magnetoresistance in layered magnetic structures with antiferromagnetic interlayer exchange',
    author: 'G. Binasch, P. Grünberg, F. Saurenbach, W. Zinn',
    year: 1989,
    venue: 'Physical Review B 39, 4828(R)',
    url: 'https://doi.org/10.1103/PhysRevB.39.4828',
    note: 'Independent discovery of GMR in Fe/Cr/Fe trilayers at Jülich, parallel to Baibich/Fert. The two groups shared the 2007 Nobel Prize.',
  },
  'moulson-herbert-2003': {
    id: 'moulson-herbert-2003',
    title: 'Electroceramics: Materials, Properties, Applications, 2nd ed.',
    author: 'Anthony J. Moulson, John M. Herbert',
    year: 2003,
    venue: 'Wiley',
    note: 'Comprehensive reference on dielectric ceramics: BaTiO₃ permittivity (εᵣ ≈ 1000–10000 near the ferroelectric Curie point of ~120 °C), X7R / Y5V multilayer capacitor formulations, breakdown fields, and temperature-coefficient classifications.',
  },

  /* ─── Ch.7–9 case-study sources ─── */
  'ieee-80211': {
    id: 'ieee-80211',
    title: 'IEEE Std 802.11-2020: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) Specifications',
    author: 'IEEE 802.11 Working Group',
    year: 2021,
    venue: 'IEEE Standards Association',
    url: 'https://standards.ieee.org/ieee/802.11/7028/',
    note: 'Defines Wi-Fi PHY/MAC. The 2.4 GHz ISM band (2.400–2.4835 GHz) and 5 GHz UNII bands are the primary operating channels; 802.11ax (Wi-Fi 6) extends operation to the 6 GHz band.',
  },
  'buffler-1993': {
    id: 'buffler-1993',
    title: 'Microwave Cooking and Processing: Engineering Fundamentals for the Food Scientist',
    author: 'Charles R. Buffler',
    year: 1993,
    venue: 'Van Nostrand Reinhold',
    note: 'Domestic microwave ovens operate at 2.450 GHz (an ISM band), coupling into the broad rotational/dielectric loss of liquid water rather than a discrete molecular resonance; magnetron output of typical home units is 700–1100 W.',
  },
  'tsuda-2013-ikaros': {
    id: 'tsuda-2013-ikaros',
    title: 'Achievement of IKAROS — Japanese deep space solar sail demonstration mission',
    author: "Yuichi Tsuda, Osamu Mori, Ryu Funase, Hirotaka Sawada, Takayuki Yamamoto, Takanao Saiki, Tatsuya Endo, Katsuhide Yonekura, Hirokazu Hoshino, Jun'ichiro Kawaguchi",
    year: 2013,
    venue: 'Acta Astronautica 82 (2), 183–188',
    url: 'https://doi.org/10.1016/j.actaastro.2012.03.032',
    note: 'IKAROS (Interplanetary Kite-craft Accelerated by Radiation Of the Sun), launched May 2010, deployed a 20 m × 20 m polyimide sail (~7.5 μm thick) and demonstrated photon-pressure acceleration of ~1.12 mm/s per day at ~1 AU during its Venus flyby cruise.',
  },
  'rontgen-1895': {
    id: 'rontgen-1895',
    title: 'Über eine neue Art von Strahlen (On a New Kind of Rays)',
    author: 'Wilhelm Conrad Röntgen',
    year: 1895,
    venue: 'Sitzungsberichte der Würzburger Physikalisch-medicinischen Gesellschaft 137, 132–141',
    note: "Discovery of X-rays, 8 November 1895. Röntgen identified the radiation passing through opaque materials and produced the first medical radiograph (his wife's hand) on 22 December 1895.",
  },
  'rappaport-2013-mmwave': {
    id: 'rappaport-2013-mmwave',
    title: 'Millimeter Wave Mobile Communications for 5G Cellular: It Will Work!',
    author: 'Theodore S. Rappaport, Shu Sun, Rimma Mayzus, Hang Zhao, Yaniv Azar, Kevin Wang, George N. Wong, Jocelyn K. Schulz, Mathew Samimi, Felix Gutierrez',
    year: 2013,
    venue: 'IEEE Access 1, 335–349',
    url: 'https://doi.org/10.1109/ACCESS.2013.2260813',
    note: '5G mmWave propagation measurements at 28 GHz and 38 GHz in urban environments; established the engineering case for mmWave cellular reuse despite ~20 dB extra path loss vs. sub-6-GHz bands.',
  },
  'hong-2001-wireless': {
    id: 'hong-2001-wireless',
    title: "Wireless: From Marconi's Black-Box to the Audion",
    author: 'Sungook Hong',
    year: 2001,
    venue: 'MIT Press',
    note: 'Historical account of the 12 December 1901 Marconi transmission from Poldhu, Cornwall to Signal Hill, Newfoundland (~3500 km), and the engineering of early spark-gap and tuned-circuit radio.',
  },
  'kaplan-hegarty-2017': {
    id: 'kaplan-hegarty-2017',
    title: 'Understanding GPS/GNSS: Principles and Applications, 3rd ed.',
    author: 'Elliott D. Kaplan, Christopher J. Hegarty (eds.)',
    year: 2017,
    venue: 'Artech House',
    note: 'GPS L1 carrier at 1575.42 MHz, L2 at 1227.60 MHz; 24+ operational satellites in six orbital planes at ~20,200 km altitude (≈12-sidereal-hour orbits); broadcast EIRP on the order of 27 dBW.',
  },
  'ewen-purcell-1951': {
    id: 'ewen-purcell-1951',
    title: 'Observation of a Line in the Galactic Radio Spectrum: Radiation from Galactic Hydrogen at 1,420 Mc./sec.',
    author: 'Harold I. Ewen, Edward M. Purcell',
    year: 1951,
    venue: 'Nature 168, 356',
    url: 'https://doi.org/10.1038/168356a0',
    note: 'First detection (March 1951) of the 21 cm (1420.406 MHz) hyperfine-transition line of neutral atomic hydrogen, predicted theoretically by van de Hulst in 1944. Foundational for HI radio astronomy.',
  },
  'ashby-2003': {
    id: 'ashby-2003',
    title: 'Relativity in the Global Positioning System',
    author: 'Neil Ashby',
    year: 2003,
    venue: 'Living Reviews in Relativity 6, 1',
    url: 'https://doi.org/10.12942/lrr-2003-1',
    note: 'Onboard GPS satellite clocks run fast by ~45.7 μs/day from gravitational time dilation (GR) and slow by ~7.2 μs/day from kinematic time dilation (SR); the net +38.6 μs/day offset is removed by tuning the satellite clock to 10.22999999543 MHz before launch (vs. the nominal 10.23 MHz).',
  },
  'schwinger-1949': {
    id: 'schwinger-1949',
    title: 'On the Classical Radiation of Accelerated Electrons',
    author: 'Julian Schwinger',
    year: 1949,
    venue: 'Physical Review 75, 1912',
    url: 'https://doi.org/10.1103/PhysRev.75.1912',
    note: 'Classical theory of synchrotron radiation: relativistic electrons in a circular orbit radiate into a forward cone of half-angle ~1/γ, with total power scaling as γ⁴/ρ² for circular orbit of radius ρ.',
  },

  /* ─── Ch.4 Capacitors ─── */
  'leyden-jar-1745': {
    id: 'leyden-jar-1745',
    title: 'The Leyden jar — independent discovery (E. G. von Kleist, October 1745; Pieter van Musschenbroek, 1746)',
    author: 'E. G. von Kleist; Pieter van Musschenbroek',
    year: 1745,
    venue: 'Correspondence and demonstrations to the Royal Society',
    note: 'First practical capacitor — a glass jar lined inside and out with metal foil, charged by friction; held a substantial charge and discharged with an audible spark.',
  },
  'volta-1782': {
    id: 'volta-1782',
    title: 'Del modo di rendere sensibilissima la più debole elettricità sia artificiale sia naturale (On the way of making the weakest electricity sensible, both artificial and natural)',
    author: 'Alessandro Volta',
    year: 1782,
    venue: 'Philosophical Transactions of the Royal Society of London 72, 237–280',
    note: "Introduces the relation Q = CV and the term 'capacity' — the linear proportionality of stored charge to applied potential, with the constant of proportionality a property of the device.",
  },

  /* ─── Ch.11 Instrumentation ─── */
  'keysight-34465a-datasheet': {
    id: 'keysight-34465a-datasheet',
    title: 'Keysight Truevolt Series Digital Multimeters — 34465A / 34470A Data Sheet',
    author: 'Keysight Technologies',
    year: 2023,
    venue: 'Keysight Technologies publication 5991-1983EN',
    url: 'https://www.keysight.com/us/en/assets/7018-04209/data-sheets/5991-1983.pdf',
    note: '6½-digit and 7½-digit bench DMMs. Specifies 1 GΩ DC input impedance on the 0.1/1/10 V ranges, true-RMS AC measurement with selectable AC bandwidth, and DC voltage accuracy of order 0.0030% of reading. Used as the canonical modern-DMM datasheet for claims about input impedance, true-RMS behaviour, and bench-instrument accuracy.',
  },
};

export type SourceKey = keyof typeof SOURCES;

/** Get a citation's display string (used by inline <Cite/> component). */
export function citeLabel(key: SourceKey, ids: SourceKey[]): string {
  const idx = ids.indexOf(key);
  if (idx === -1) return '?';
  return String(idx + 1);
}
